wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1703869292.98285
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 98
      - 100
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 98
      - 100
      3:
      - 23
      4: 3.10.6
      5: 0.16.1
      6: 4.36.2
      8:
      - 5
      13: linux-x86_64
dataset_name:
  desc: null
  value: samsum
dataset_config_name:
  desc: null
  value: null
train_file:
  desc: null
  value: null
validation_file:
  desc: null
  value: null
validation_split_percentage:
  desc: null
  value: 5
model_name_or_path:
  desc: null
  value: LoftQ/Llama-2-13b-hf-4bit-64rank
config_name:
  desc: null
  value: null
tokenizer_name:
  desc: null
  value: null
use_slow_tokenizer:
  desc: null
  value: false
per_device_train_batch_size:
  desc: null
  value: 4
per_device_eval_batch_size:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 0.0005
weight_decay:
  desc: null
  value: 0.1
num_train_epochs:
  desc: null
  value: 5
max_train_steps:
  desc: null
  value: 4605
gradient_accumulation_steps:
  desc: null
  value: 4
lr_scheduler_type:
  desc: null
  value: linear
num_warmup_steps:
  desc: null
  value: 100
output_dir:
  desc: null
  value: exp_results/with_prompt_high_lr_linear_decay
seed:
  desc: null
  value: 202
model_type:
  desc: null
  value: null
ignore_pad_token_for_loss:
  desc: null
  value: true
max_source_length:
  desc: null
  value: 256
max_target_length:
  desc: null
  value: 256
pad_to_max_length:
  desc: null
  value: true
preprocessing_num_workers:
  desc: null
  value: null
overwrite_cache:
  desc: null
  value: false
no_keep_linebreaks:
  desc: null
  value: false
push_to_hub:
  desc: null
  value: false
hub_model_id:
  desc: null
  value: null
hub_token:
  desc: null
  value: null
trust_remote_code:
  desc: null
  value: false
checkpointing_steps:
  desc: null
  value: '100'
resume_from_checkpoint:
  desc: null
  value: null
with_tracking:
  desc: null
  value: true
report_to:
  desc: null
  value: wandb
low_cpu_mem_usage:
  desc: null
  value: false
temperature:
  desc: null
  value: 0.8
k:
  desc: null
  value: 40
p:
  desc: null
  value: 0.95
adapter_name_or_path:
  desc: null
  value: null
